#None=value is not assigned to an variable
#Numeric=int,float,complex,bool
#sequence=list,set,tuple,range,string
#mapping=dictionary
num=2
b=2.3
n=6+9j
print(type(num))
print(type(b))
print(type(n))
a=6.7
x=int(a)
print(x)
print(float(x))
print(complex(num,x))
y=num<x
print(y)
print(type(y))
l=[2,3,4]
print(type(l))
s={1,2,3,4,5}
print(type(s))
print(s)
t=(9,7,6,4)
print(type(t))
str='hello'
st="pravali"
print(type(st))
print(type(str))
print(range(10))
print(tuple(range(10)))
print(list(range(2,10,2)))
print(type(range(2,10)))
dict={'one':1,'two':2}
print(dict)
print(type(dict))
print(dict.keys())
print(dict.values())
print(dict['one'])
print(dict.get('two'))